export const IDOLS = [
    {
        id: 1,
        name: "Leo",
        jpName: "赤城 玲央",
        color: "from-red-500 to-orange-600",
        bgAccent: "bg-red-100",
        textAccent: "text-red-600",
        catchphrase: "俺についてこい!世界を照らす情熱の太陽",
        type: "Passion",
        image: "https://i.ibb.co/P7k5TNW/idol1.png",
        thumbnail: "https://i.ibb.co/Y4jfP5RJ/idol11.png",
        stats: { vocal: 95, dance: 90, visual: 85 }
    },
    {
        id: 2,
        name: "Kai",
        jpName: "氷川 櫂",
        color: "from-blue-500 to-cyan-500",
        bgAccent: "bg-blue-100",
        textAccent: "text-blue-600",
        catchphrase: "冷静沈着、計算尽くのパーフェクト・ブルー",
        type: "Cool",
        image: "https://i.ibb.co/1YHks0cf/idol2.png",
        thumbnail: "https://i.ibb.co/Rq96dM6/idol12.png",
        stats: { vocal: 90, dance: 85, visual: 95 }
    },
    {
        id: 3,
        name: "Hinata",
        jpName: "星野 日向",
        color: "from-yellow-300 to-orange-400",
        bgAccent: "bg-yellow-100",
        textAccent: "text-yellow-600",
        catchphrase: "みんなの笑顔の充電器!ハッピー全開ビタミン",
        type: "Pop",
        image: "https://i.ibb.co/W4k423Sy/idol3.png",
        thumbnail: "https://i.ibb.co/BRnSKcc/idol13.png",
        stats: { vocal: 85, dance: 95, visual: 90 }
    },
    {
        id: 4,
        name: "Sou",
        jpName: "双葉 奏",
        color: "from-green-400 to-emerald-500",
        bgAccent: "bg-green-100",
        textAccent: "text-green-600",
        catchphrase: "君の心を優しく包む、癒しの森のマイナスイオン",
        type: "Healing",
        image: "https://i.ibb.co/MDCpfWpm/idol4.png",
        thumbnail: "https://i.ibb.co/99FksRSM/idol14.png",
        stats: { vocal: 92, dance: 75, visual: 88 }
    },
    {
        id: 5,
        name: "Nico",
        jpName: "桃瀬 にこ",
        color: "from-pink-300 to-rose-400",
        bgAccent: "bg-pink-100",
        textAccent: "text-pink-500",
        catchphrase: "あざとくても許してね?ラブリー全開、国民的弟",
        type: "Cute",
        image: "https://i.ibb.co/R4Qnk9qD/idol5.png",
        thumbnail: "https://i.ibb.co/HL15bdpn/idol16.png",
        stats: { vocal: 80, dance: 85, visual: 100 }
    },
    {
        id: 6,
        name: "Shion",
        jpName: "藤崎 紫音",
        color: "from-purple-500 to-violet-600",
        bgAccent: "bg-purple-100",
        textAccent: "text-purple-600",
        catchphrase: "今夜は眠らせない…魅惑のミステリアス・ナイト",
        type: "Sexy",
        image: "https://i.ibb.co/CKw7CPqF/idol6.png",
        thumbnail: "https://i.ibb.co/xqRSnCyD/idol15.png",
        stats: { vocal: 98, dance: 80, visual: 92 }
    },
    {
        id: 7,
        name: "Gaku",
        jpName: "豪田 岳",
        color: "from-orange-500 to-amber-600",
        bgAccent: "bg-orange-100",
        textAccent: "text-orange-600",
        catchphrase: "燃え尽きるまで騒ごうぜ!限界突破のワイルド・ビート",
        type: "Wild",
        image: "https://i.ibb.co/7trzD9Jr/idol7.png",
        thumbnail: "https://i.ibb.co/yBqzWbB2/idol18.png",
        stats: { vocal: 88, dance: 98, visual: 80 }
    },
    {
        id: 8,
        name: "Sena",
        jpName: "雨宮 聖奈",
        color: "from-cyan-300 to-sky-400",
        bgAccent: "bg-sky-100",
        textAccent: "text-sky-600",
        catchphrase: "ガラスの靴を持って迎えにいくよ。君だけのクリスタル・プリンス",
        type: "Prince",
        image: "https://i.ibb.co/67q5M3vM/idol8.png",
        thumbnail: "https://i.ibb.co/WN0mvx06/idol17.png",
        stats: { vocal: 94, dance: 88, visual: 96 }
    },
    {
        id: 9,
        name: "Jay",
        jpName: "若林 ジェイ",
        color: "from-lime-400 to-green-500",
        bgAccent: "bg-lime-100",
        textAccent: "text-lime-600",
        catchphrase: "規格外の異端児、常識なんてラップで吹き飛ばす",
        type: "Unique",
        image: "https://i.ibb.co/JRkG41mt/idol9.png",
        thumbnail: "https://i.ibb.co/GvCLhHyv/idol19.png",
        stats: { vocal: 90, dance: 96, visual: 85 }
    },
    {
        id: 10,
        name: "Haku",
        jpName: "白鳥 珀",
        color: "from-gray-200 to-slate-400",
        bgAccent: "bg-gray-100",
        textAccent: "text-slate-600",
        catchphrase: "誰も触れられない絶対聖域(サンクチュアリ)。奇跡のイノセンス",
        type: "Mystery",
        image: "https://i.ibb.co/q2dYCQT/idol10.png",
        thumbnail: "https://i.ibb.co/4ZWC3wfS/idol20.png",
        stats: { vocal: 100, dance: 90, visual: 100 }
    }
];

export const NEWS_DATA = [
    { date: '2024.10.25', cat: 'EVENT', title: 'ハロウィン限定イベント「Sweet Ghost」開催決定!' },
    { date: '2024.10.18', cat: 'UPDATE', title: '新キャラクター「Kira」参戦!キャラクターページ更新' },
    { date: '2024.10.10', cat: 'MEDIA', title: '公式Webラジオ第12回配信開始' },
    { date: '2024.10.01', cat: 'INFO', title: 'システムメンテナンスのお知らせ' },
];
